package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"html/template"
	"log"
	"net"
	"net/http"
	"os"
	"sort"
	"strconv"
	"strings"
	"time"
)

const (
	viewerReadHeaderTimeout = 10 * time.Second
	viewerIdleTimeout       = 60 * time.Second
)

type playerSnapshot struct {
	SteamID64 string  `json:"steamid64"`
	Name      string  `json:"name"`
	Team      string  `json:"team"`
	Alive     bool    `json:"alive"`
	Health    int     `json:"health"`
	Armor     int     `json:"armor"`
	Place     string  `json:"place"`
	X         float64 `json:"x"`
	Y         float64 `json:"y"`
	Z         float64 `json:"z"`
	Yaw       float64 `json:"yaw"`
	FlashLeft float64 `json:"flash_left_seconds"`
}

type damageEvent struct {
	Tick       int     `json:"tick"`
	Time       float64 `json:"time_seconds"`
	Attacker   string  `json:"attacker"`
	AttackerID string  `json:"attacker_steamid64"`
	Weapon     string  `json:"weapon"`
	HealthDmg  int     `json:"health_damage"`
	ArmorDmg   int     `json:"armor_damage"`
	HitGroup   string  `json:"hit_group"`
	PlayerHP   int     `json:"victim_health_after"`
}

type killEvent struct {
	Tick          int     `json:"tick"`
	Time          float64 `json:"time_seconds"`
	Round         int     `json:"round"`
	Killer        string  `json:"killer"`
	KillerID      string  `json:"killer_steamid64"`
	Victim        string  `json:"victim"`
	VictimID      string  `json:"victim_steamid64"`
	Weapon        string  `json:"weapon"`
	Headshot      bool    `json:"headshot"`
	ThroughSmoke  bool    `json:"through_smoke"`
	Wallbang      bool    `json:"wallbang"`
	DistanceUnits float64 `json:"distance_units"`
	KillerTeam    string  `json:"killer_team"`
	VictimTeam    string  `json:"victim_team"`
}

type deathRecord struct {
	Index                 int              `json:"index"`
	Tick                  int              `json:"tick"`
	Time                  float64          `json:"time_seconds"`
	Round                 int              `json:"round"`
	RoundTime             float64          `json:"round_time_seconds"`
	ScoreCT               int              `json:"score_ct_before_round_end"`
	ScoreT                int              `json:"score_t_before_round_end"`
	Target                playerSnapshot   `json:"target"`
	Killer                playerSnapshot   `json:"killer"`
	Weapon                string           `json:"weapon"`
	Headshot              bool             `json:"headshot"`
	ThroughSmoke          bool             `json:"through_smoke"`
	Wallbang              bool             `json:"wallbang"`
	DistanceUnits         float64          `json:"distance_units"`
	AssistedFlash         bool             `json:"assisted_flash"`
	AttackerBlind         bool             `json:"attacker_blind"`
	NoScope               bool             `json:"no_scope"`
	BombPlanted           bool             `json:"bomb_planted"`
	BombSite              string           `json:"bomb_site,omitempty"`
	AliveFriendly         int              `json:"alive_friendly"`
	AliveEnemy            int              `json:"alive_enemy"`
	NearbyFriendly600     []playerSnapshot `json:"nearby_friendly_600"`
	NearestFriendly       *playerSnapshot  `json:"nearest_friendly,omitempty"`
	NearestFriendlyDist   float64          `json:"nearest_friendly_distance_units,omitempty"`
	DamageBeforeDeath     []damageEvent    `json:"damage_before_death_10s"`
	KillsPrevious10s      []killEvent      `json:"kills_previous_10s"`
	LastTargetShotSeconds *float64         `json:"last_target_shot_seconds_before_death,omitempty"`
	TargetShotsLast5s     int              `json:"target_shots_last_5s"`
	FirstDeathOfTeam      bool             `json:"first_death_of_team"`
	TradedBy              *killEvent       `json:"traded_by_teammate_within_5s,omitempty"`
	TradedAfterSeconds    *float64         `json:"traded_after_seconds,omitempty"`
}

type analysisData struct {
	Demo         string            `json:"demo"`
	Map          string            `json:"map"`
	Tickrate     float64           `json:"tickrate"`
	TargetID     string            `json:"target_steamid64"`
	TargetName   string            `json:"target_name"`
	Deaths       []deathRecord     `json:"deaths"`
	AllKills     []killEvent       `json:"all_kills"`
	RoundWinners map[string]string `json:"round_winners"`
}

type server struct {
	data    analysisData
	summary summary
	places  []string
	tmpl    *template.Template
}

type pageData struct {
	Analysis analysisData
	Summary  summary
	Places   []string
	Deaths   []deathRecord
	Selected *deathRecord
}

type summary struct {
	Deaths       int
	Untraded     int
	Isolated     int
	LowHP        int
	PostKill     int
	Opening      int
	SideEntrance int
	TSideLower   int
}

func main() {
	var jsonPath string
	var addr string
	var allowPublic bool
	flag.StringVar(&jsonPath, "json", "data/analysis/MarcusN1-deaths.json", "analysis JSON generated by death_analysis.go")
	flag.StringVar(&addr, "addr", "127.0.0.1:8090", "HTTP listen address")
	flag.BoolVar(&allowPublic, "allow-public", false, "allow binding to a non-loopback address (exposes demo analysis to the network)")
	flag.Parse()

	if err := listenGuard(addr, allowPublic); err != nil {
		log.Fatalf("zv-analysis-viewer: %v", err)
	}

	data, err := loadAnalysis(jsonPath)
	if err != nil {
		log.Fatal(err)
	}
	s := &server{
		data: data,
		// The analysis is immutable once loaded, so derive the summary and place
		// breakdown once instead of recomputing them on every index request.
		summary: summarize(data.Deaths),
		places:  places(data.Deaths),
		tmpl: template.Must(template.New("viewer").Funcs(template.FuncMap{
			"f1":       f1,
			"f0":       f0,
			"issues":   issues,
			"hasTrade": hasTrade,
			"delta":    delta,
			"postKill": targetKillPrevious10s,
			"winner":   func(round int) string { return data.RoundWinners[strconv.Itoa(round)] },
		}).Parse(viewerTemplate)),
	}

	mux := http.NewServeMux()
	mux.HandleFunc("/", s.handleIndex)
	mux.HandleFunc("/deaths", s.handleDeaths)
	mux.HandleFunc("/death/", s.handleDeath)
	mux.HandleFunc("/healthz", func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte("ok\n"))
	})

	log.Printf("zv-analysis-viewer: http://%s", addr)
	if err := newViewerHTTPServer(addr, mux).ListenAndServe(); err != nil {
		log.Fatal(err)
	}
}

func newViewerHTTPServer(addr string, handler http.Handler) *http.Server {
	return &http.Server{
		Addr:              addr,
		Handler:           handler,
		ReadHeaderTimeout: viewerReadHeaderTimeout,
		IdleTimeout:       viewerIdleTimeout,
	}
}

// listenGuard refuses a non-loopback bind unless allowPublic is set. An empty
// host (e.g. ":8090") binds all interfaces and counts as non-loopback.
func listenGuard(addr string, allowPublic bool) error {
	if allowPublic {
		return nil
	}
	host, _, err := net.SplitHostPort(addr)
	if err != nil {
		return fmt.Errorf("parse listen address %q: %w", addr, err)
	}
	if host == "localhost" {
		return nil
	}
	if ip := net.ParseIP(host); ip != nil && ip.IsLoopback() {
		return nil
	}
	return fmt.Errorf("non-loopback listen address %q requires --allow-public", addr)
}

func loadAnalysis(path string) (analysisData, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return analysisData{}, err
	}
	var data analysisData
	if err := json.Unmarshal(b, &data); err != nil {
		return analysisData{}, err
	}
	sort.Slice(data.Deaths, func(i, j int) bool { return data.Deaths[i].Index < data.Deaths[j].Index })
	return data, nil
}

func (s *server) handleIndex(w http.ResponseWriter, r *http.Request) {
	if r.URL.Path != "/" {
		http.NotFound(w, r)
		return
	}
	deaths := filterDeaths(s.data.Deaths, r)
	var selected *deathRecord
	if len(deaths) > 0 {
		selected = &deaths[0]
	}
	s.render(w, "page", pageData{
		Analysis: s.data,
		Summary:  s.summary,
		Places:   s.places,
		Deaths:   deaths,
		Selected: selected,
	})
}

func (s *server) handleDeaths(w http.ResponseWriter, r *http.Request) {
	s.render(w, "deathList", pageData{Deaths: filterDeaths(s.data.Deaths, r)})
}

func (s *server) handleDeath(w http.ResponseWriter, r *http.Request) {
	id := strings.TrimPrefix(r.URL.Path, "/death/")
	index, err := strconv.Atoi(id)
	if err != nil {
		http.NotFound(w, r)
		return
	}
	for i := range s.data.Deaths {
		if s.data.Deaths[i].Index == index {
			s.render(w, "deathDetail", pageData{Selected: &s.data.Deaths[i]})
			return
		}
	}
	http.NotFound(w, r)
}

func (s *server) render(w http.ResponseWriter, name string, data pageData) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if err := s.tmpl.ExecuteTemplate(w, name, data); err != nil {
		log.Printf("zv-analysis-viewer: render %s: %v", name, err)
		http.Error(w, "internal server error", http.StatusInternalServerError)
	}
}

func filterDeaths(all []deathRecord, r *http.Request) []deathRecord {
	side := r.URL.Query().Get("side")
	place := r.URL.Query().Get("place")
	issue := r.URL.Query().Get("issue")
	q := strings.ToLower(strings.TrimSpace(r.URL.Query().Get("q")))
	out := make([]deathRecord, 0, len(all))
	for _, d := range all {
		if side != "" && d.Target.Team != side {
			continue
		}
		if place != "" && d.Target.Place != place {
			continue
		}
		if issue != "" && !matchesIssue(d, issue) {
			continue
		}
		if q != "" && !strings.Contains(strings.ToLower(searchText(d)), q) {
			continue
		}
		out = append(out, d)
	}
	return out
}

func matchesIssue(d deathRecord, issue string) bool {
	switch issue {
	case "untraded":
		return d.TradedBy == nil
	case "isolated":
		return len(d.NearbyFriendly600) == 0
	case "lowhp":
		return d.Target.Health <= 20
	case "postkill":
		return targetKillPrevious10s(d)
	case "opening":
		return d.FirstDeathOfTeam
	default:
		return true
	}
}

func searchText(d deathRecord) string {
	return strings.Join([]string{
		d.Target.Team,
		d.Target.Place,
		d.Killer.Name,
		d.Killer.Place,
		d.Weapon,
		fmt.Sprintf("r%d", d.Round),
	}, " ")
}

func summarize(deaths []deathRecord) summary {
	var s summary
	s.Deaths = len(deaths)
	for _, d := range deaths {
		if d.TradedBy == nil {
			s.Untraded++
		}
		if len(d.NearbyFriendly600) == 0 {
			s.Isolated++
		}
		if d.Target.Health <= 20 {
			s.LowHP++
		}
		if targetKillPrevious10s(d) {
			s.PostKill++
		}
		if d.FirstDeathOfTeam {
			s.Opening++
		}
		if d.Target.Place == "SideEntrance" {
			s.SideEntrance++
		}
		if d.Target.Place == "TSideLower" {
			s.TSideLower++
		}
	}
	return s
}

func places(deaths []deathRecord) []string {
	seen := map[string]bool{}
	for _, d := range deaths {
		if d.Target.Place != "" {
			seen[d.Target.Place] = true
		}
	}
	out := make([]string, 0, len(seen))
	for p := range seen {
		out = append(out, p)
	}
	sort.Strings(out)
	return out
}

func issues(d deathRecord) []string {
	var out []string
	if d.TradedBy == nil {
		out = append(out, "sin trade")
	}
	if len(d.NearbyFriendly600) == 0 {
		out = append(out, "aislado")
	}
	if d.Target.Health <= 20 {
		out = append(out, "low HP")
	}
	if targetKillPrevious10s(d) {
		out = append(out, "post-kill")
	}
	if d.FirstDeathOfTeam {
		out = append(out, "opening death")
	}
	return out
}

func targetKillPrevious10s(d deathRecord) bool {
	for _, k := range d.KillsPrevious10s {
		if k.KillerID == d.Target.SteamID64 {
			return true
		}
	}
	return false
}

func hasTrade(d deathRecord) bool {
	return d.TradedBy != nil
}

func delta(deathTime, eventTime float64) float64 {
	return deathTime - eventTime
}

func f0(v float64) string {
	return fmt.Sprintf("%.0f", v)
}

func f1(v float64) string {
	return fmt.Sprintf("%.1f", v)
}

const viewerTemplate = `
{{define "page"}}
<!doctype html>
<html lang="es">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Analisis de muertes - {{.Analysis.TargetName}}</title>
  <script src="https://unpkg.com/htmx.org@1.9.12"></script>
  <style>
    :root {
      color-scheme: light;
      --bg: #f7f8fa;
      --panel: #ffffff;
      --panel-2: #eef2f6;
      --text: #17202a;
      --muted: #64748b;
      --line: #d8e0e8;
      --accent: #117c6f;
      --accent-2: #b83242;
      --warn: #9b5a00;
      --ok: #236c3d;
    }
    * { box-sizing: border-box; }
    body {
      margin: 0;
      font-family: Inter, ui-sans-serif, system-ui, -apple-system, Segoe UI, sans-serif;
      background: var(--bg);
      color: var(--text);
      letter-spacing: 0;
    }
    header {
      border-bottom: 1px solid var(--line);
      background: var(--panel);
      padding: 18px 24px 16px;
    }
    .topline {
      display: flex;
      align-items: end;
      justify-content: space-between;
      gap: 16px;
      max-width: 1440px;
      margin: 0 auto;
    }
    h1 { margin: 0; font-size: 24px; line-height: 1.15; }
    .sub { margin-top: 6px; color: var(--muted); font-size: 13px; }
    .layout {
      max-width: 1440px;
      margin: 0 auto;
      padding: 18px 24px 28px;
    }
    .metrics {
      display: grid;
      grid-template-columns: repeat(6, minmax(120px, 1fr));
      gap: 10px;
      margin-bottom: 14px;
    }
    .metric {
      background: var(--panel);
      border: 1px solid var(--line);
      border-radius: 8px;
      padding: 12px;
      min-height: 78px;
    }
    .metric b { display: block; font-size: 24px; line-height: 1; margin-bottom: 8px; }
    .metric span { color: var(--muted); font-size: 12px; }
    .filters {
      display: grid;
      grid-template-columns: 1fr 130px 180px 180px;
      gap: 10px;
      margin-bottom: 14px;
    }
    input, select {
      width: 100%;
      height: 40px;
      border: 1px solid var(--line);
      border-radius: 6px;
      padding: 0 10px;
      background: var(--panel);
      color: var(--text);
      font: inherit;
    }
    .workspace {
      display: grid;
      grid-template-columns: minmax(360px, 0.82fr) minmax(520px, 1.18fr);
      gap: 14px;
      align-items: start;
    }
    .panel {
      background: var(--panel);
      border: 1px solid var(--line);
      border-radius: 8px;
      overflow: hidden;
    }
    .panel h2 {
      margin: 0;
      padding: 14px 16px;
      border-bottom: 1px solid var(--line);
      font-size: 15px;
    }
    .death-list {
      display: grid;
      gap: 0;
      max-height: calc(100vh - 310px);
      min-height: 420px;
      overflow: auto;
    }
    .death-row {
      display: grid;
      grid-template-columns: 52px 1fr auto;
      gap: 10px;
      align-items: center;
      width: 100%;
      border: 0;
      border-bottom: 1px solid var(--line);
      padding: 12px 14px;
      background: transparent;
      color: inherit;
      text-align: left;
      cursor: pointer;
      font: inherit;
    }
    .death-row:hover { background: #f0f5f8; }
    .idx {
      width: 38px;
      height: 32px;
      border-radius: 6px;
      display: grid;
      place-items: center;
      background: var(--panel-2);
      font-weight: 700;
    }
    .mainline { font-weight: 700; font-size: 14px; }
    .meta { color: var(--muted); font-size: 12px; margin-top: 3px; }
    .tags { display: flex; gap: 5px; flex-wrap: wrap; margin-top: 8px; }
    .tag {
      border: 1px solid var(--line);
      border-radius: 999px;
      padding: 2px 7px;
      font-size: 11px;
      color: #334155;
      background: #fbfcfd;
      white-space: nowrap;
    }
    .tag.bad { border-color: #efc6cc; color: var(--accent-2); background: #fff5f6; }
    .tag.warn { border-color: #e7c983; color: var(--warn); background: #fff9eb; }
    .tag.ok { border-color: #b9dfc8; color: var(--ok); background: #f2fbf5; }
    .score { color: var(--muted); font-size: 12px; text-align: right; white-space: nowrap; }
    .detail { padding: 16px; }
    .detail-head {
      display: flex;
      justify-content: space-between;
      gap: 14px;
      padding-bottom: 14px;
      border-bottom: 1px solid var(--line);
    }
    .detail h3 { margin: 0; font-size: 20px; }
    .verdict {
      margin-top: 12px;
      padding: 12px;
      border-left: 4px solid var(--accent-2);
      background: #fff7f7;
      border-radius: 6px;
      line-height: 1.45;
    }
    .grid2 {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 10px;
      margin-top: 14px;
    }
    .fact {
      border: 1px solid var(--line);
      border-radius: 8px;
      padding: 10px;
      min-height: 68px;
      background: #fcfdfe;
    }
    .fact span { display: block; color: var(--muted); font-size: 12px; margin-bottom: 5px; }
    .fact b { font-size: 15px; }
    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 14px;
      font-size: 13px;
    }
    th, td {
      border-bottom: 1px solid var(--line);
      padding: 8px 6px;
      text-align: left;
      vertical-align: top;
    }
    th { color: var(--muted); font-weight: 600; }
    .empty { padding: 18px; color: var(--muted); }
    @media (max-width: 980px) {
      .metrics { grid-template-columns: repeat(2, minmax(130px, 1fr)); }
      .filters { grid-template-columns: 1fr 1fr; }
      .workspace { grid-template-columns: 1fr; }
      .death-list { max-height: none; min-height: 0; }
      .grid2 { grid-template-columns: 1fr; }
      header, .layout { padding-left: 14px; padding-right: 14px; }
    }
  </style>
</head>
<body>
  <header>
    <div class="topline">
      <div>
        <h1>{{.Analysis.TargetName}} - analisis de muertes</h1>
        <div class="sub">{{.Analysis.Map}} · {{.Analysis.TargetID}} · {{f0 .Analysis.Tickrate}} tick · {{.Summary.Deaths}} muertes analizadas</div>
      </div>
    </div>
  </header>
  <main class="layout">
    <section class="metrics" aria-label="Metricas principales">
      <div class="metric"><b>{{.Summary.Untraded}}/{{.Summary.Deaths}}</b><span>muertes sin trade en 5s</span></div>
      <div class="metric"><b>{{.Summary.Isolated}}/{{.Summary.Deaths}}</b><span>sin teammate a 600u</span></div>
      <div class="metric"><b>{{.Summary.LowHP}}/{{.Summary.Deaths}}</b><span>muertes con 20 HP o menos</span></div>
      <div class="metric"><b>{{.Summary.PostKill}}/{{.Summary.Deaths}}</b><span>tras kill propia en 10s</span></div>
      <div class="metric"><b>{{.Summary.Opening}}/{{.Summary.Deaths}}</b><span>opening deaths de su equipo</span></div>
      <div class="metric"><b>{{.Summary.SideEntrance}} + {{.Summary.TSideLower}}</b><span>SideEntrance y TSideLower</span></div>
    </section>

    <form class="filters"
      hx-get="/deaths"
      hx-target="#death-list"
      hx-trigger="input changed delay:180ms, change">
      <input name="q" type="search" placeholder="Buscar ronda, killer, arma o zona">
      <select name="side">
        <option value="">Side: todos</option>
        <option value="T">T</option>
        <option value="CT">CT</option>
      </select>
      <select name="issue">
        <option value="">Problema: todos</option>
        <option value="untraded">Sin trade</option>
        <option value="isolated">Aislado</option>
        <option value="lowhp">Low HP</option>
        <option value="postkill">Post-kill</option>
        <option value="opening">Opening death</option>
      </select>
      <select name="place">
        <option value="">Zona: todas</option>
        {{range .Places}}<option value="{{.}}">{{.}}</option>{{end}}
      </select>
    </form>

    <section class="workspace">
      <div class="panel">
        <h2>Muertes</h2>
        <div id="death-list" class="death-list">
          {{template "deathList" .}}
        </div>
      </div>
      <div class="panel">
        <div id="death-detail">
          {{template "deathDetail" .}}
        </div>
      </div>
    </section>
  </main>
</body>
</html>
{{end}}

{{define "deathList"}}
{{if .Deaths}}
  {{range .Deaths}}
  <button class="death-row" hx-get="/death/{{.Index}}" hx-target="#death-detail">
    <div class="idx">#{{.Index}}</div>
    <div>
      <div class="mainline">R{{.Round}} · {{.Target.Team}} {{.Target.Place}} · muere vs {{.Killer.Name}}</div>
      <div class="meta">{{.Weapon}} · {{f1 .RoundTime}}s de ronda · {{.AliveFriendly}}v{{.AliveEnemy}} vivos · teammate mas cercano {{f0 .NearestFriendlyDist}}u</div>
      <div class="tags">
        {{range issues .}}<span class="tag bad">{{.}}</span>{{end}}
        {{if hasTrade .}}<span class="tag ok">tradeado</span>{{end}}
        {{if .Headshot}}<span class="tag warn">headshot</span>{{end}}
      </div>
    </div>
    <div class="score">{{.ScoreCT}}-{{.ScoreT}}<br>{{if winner .Round}}gana {{winner .Round}}{{end}}</div>
  </button>
  {{end}}
{{else}}
  <div class="empty">No hay muertes con esos filtros.</div>
{{end}}
{{end}}

{{define "deathDetail"}}
{{with .Selected}}
<div class="detail">
  <div class="detail-head">
    <div>
      <h3>#{{.Index}} · Ronda {{.Round}} · {{.Target.Team}} {{.Target.Place}}</h3>
      <div class="sub">{{f1 .Time}}s demo · {{f1 .RoundTime}}s ronda · score {{.ScoreCT}}-{{.ScoreT}} · {{if winner .Round}}gana {{winner .Round}}{{else}}winner n/d{{end}}</div>
    </div>
    <div class="tags">
      {{range issues .}}<span class="tag bad">{{.}}</span>{{end}}
      {{if hasTrade .}}<span class="tag ok">tradeado</span>{{end}}
    </div>
  </div>

  <div class="verdict">
    {{if .FirstDeathOfTeam}}
      Opening death: toma el primer contacto de su equipo en {{.Target.Place}}.
    {{else if postKill .}}
      Post-kill death: ya habia generado valor y vuelve a morir antes de resetear la situacion.
    {{else if eq (len .NearbyFriendly600) 0}}
      Duelo aislado: no tenia un teammate vivo a menos de 600 unidades para tradear.
    {{else}}
      Muerte revisable por timing y microduelo: habia apoyo cercano, pero el intercambio no se convierte.
    {{end}}
    {{if le .Target.Health 20}} Llega al golpe final con {{.Target.Health}} HP: debia jugar para trade/info, no como primer contacto.{{end}}
  </div>

  <div class="grid2">
    <div class="fact"><span>Killer</span><b>{{.Killer.Name}} · {{.Weapon}}</b><div class="meta">{{.Killer.Team}} {{.Killer.Place}} · {{.Killer.Health}} HP · distancia {{f0 .DistanceUnits}}u</div></div>
    <div class="fact"><span>Estado de MarcusN1</span><b>{{.Target.Health}} HP · {{.Target.Armor}} armor</b><div class="meta">{{.TargetShotsLast5s}} disparos en 5s · {{with .LastTargetShotSeconds}}ultimo disparo hace {{f1 .}}s{{else}}sin disparo reciente{{end}}</div></div>
    <div class="fact"><span>Apoyo cercano</span><b>{{len .NearbyFriendly600}} teammate(s) a 600u</b><div class="meta">{{if .NearestFriendly}}{{.NearestFriendly.Name}} a {{f0 .NearestFriendlyDist}}u en {{.NearestFriendly.Place}}{{else}}sin teammate vivo{{end}}</div></div>
    <div class="fact"><span>Trade</span><b>{{if .TradedBy}}Si, por {{.TradedBy.Killer}}{{else}}No tradeado{{end}}</b><div class="meta">{{with .TradedAfterSeconds}}trade en {{f1 .}}s{{else}}sin respuesta en 5s{{end}}</div></div>
  </div>

  <table>
    <thead><tr><th>Daño previo</th><th>Atacante</th><th>Arma</th><th>Daño</th><th>HP after</th></tr></thead>
    <tbody>
      {{range .DamageBeforeDeath}}
      <tr><td>-{{f1 (delta $.Selected.Time .Time)}}s</td><td>{{.Attacker}}</td><td>{{.Weapon}}</td><td>{{.HealthDmg}}</td><td>{{.PlayerHP}}</td></tr>
      {{else}}
      <tr><td colspan="5">Sin daño registrado en la ventana previa.</td></tr>
      {{end}}
    </tbody>
  </table>

  <table>
    <thead><tr><th>Kills previas en 10s</th><th>Killer</th><th>Victima</th><th>Arma</th></tr></thead>
    <tbody>
      {{range .KillsPrevious10s}}
      <tr><td>-{{f1 (delta $.Selected.Time .Time)}}s</td><td>{{.Killer}}</td><td>{{.Victim}}</td><td>{{.Weapon}}</td></tr>
      {{else}}
      <tr><td colspan="4">No hubo kills en los 10s previos.</td></tr>
      {{end}}
    </tbody>
  </table>
</div>
{{else}}
<div class="empty">Selecciona una muerte para ver el detalle.</div>
{{end}}
{{end}}
`
