package mcpserver

import (
	"context"
	"net/http"
	"sort"
	"testing"

	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// TestToolContract asserts the registered tool surface: every expected tool is
// present with a description, its input JSON Schema exposes exactly the expected
// (described) properties with the right required set, and its output schema
// carries the expected top-level fields. This is the machine-facing contract an
// agent depends on, generated by the SDK from the Go request/response structs.
func TestToolContract(t *testing.T) {
	// An empty stub suffices: ListTools inspects registered schemas, not handlers.
	cs := newMCPSession(t, depsFor(t, newStubServer(t, http.NewServeMux())))
	res, err := cs.ListTools(context.Background(), nil)
	if err != nil {
		t.Fatalf("ListTools: %v", err)
	}
	byName := make(map[string]*mcp.Tool, len(res.Tools))
	for _, tool := range res.Tools {
		byName[tool.Name] = tool
	}

	type contract struct {
		inputRequired []string
		inputOptional []string
		outputFields  []string
	}
	want := map[string]contract{
		"get_capabilities": {outputFields: []string{"record", "render", "compose", "stream"}},
		"list_presets":     {outputFields: []string{"default", "presets"}},
		"list_jobs":        {inputOptional: []string{"limit"}, outputFields: []string{"jobs"}},
		"get_job":          {inputRequired: []string{"job_id"}, outputFields: []string{"id", "status"}},
		"get_roster":       {inputRequired: []string{"job_id"}, outputFields: []string{"players", "match"}},
		"get_plan":         {inputRequired: []string{"job_id"}, outputFields: []string{"segments", "target"}},
		"get_moments":      {inputRequired: []string{"job_id"}, outputFields: []string{"moments", "job_id"}},
		"next_step":        {inputRequired: []string{"job_id"}, inputOptional: []string{"variant"}, outputFields: []string{"step", "actionable", "label", "suggested_tool", "suggested_args_hint"}},
		"create_job":       {inputRequired: []string{"demo_path"}, inputOptional: []string{"target_steamid"}, outputFields: []string{"id", "poll_hint_seconds"}},
		"start_parse":      {inputRequired: []string{"job_id", "target_steamid"}, outputFields: []string{"id", "poll_hint_seconds"}},
		"start_recording":  {inputRequired: []string{"job_id"}, inputOptional: []string{"preset", "segment_ids"}, outputFields: []string{"id", "poll_hint_seconds"}},
		"start_compose":    {inputRequired: []string{"job_id"}, outputFields: []string{"id", "poll_hint_seconds"}},
		"start_render":     {inputRequired: []string{"job_id", "variant"}, outputFields: []string{"id", "poll_hint_seconds"}},
		"get_render":       {inputRequired: []string{"job_id", "variant"}, outputFields: []string{"job_id", "variant", "status"}},
		"download_final":   {inputRequired: []string{"job_id", "out_path"}, outputFields: []string{"path", "bytes_written"}},
	}

	if len(byName) != len(want) {
		t.Errorf("registered %d tools, want %d\n got: %v", len(byName), len(want), toolNames(byName))
	}

	for name, c := range want {
		t.Run(name, func(t *testing.T) {
			tool, ok := byName[name]
			if !ok {
				t.Fatalf("tool %q not registered", name)
			}
			if tool.Description == "" {
				t.Error("tool has no description")
			}

			props := schemaProperties(t, tool.InputSchema)
			required := schemaRequired(tool.InputSchema)

			wantProps := append(append([]string{}, c.inputRequired...), c.inputOptional...)
			if got := keys(props); !sameSet(got, wantProps) {
				t.Errorf("input properties = %v, want %v", got, wantProps)
			}
			for propName, raw := range props {
				prop, _ := raw.(map[string]any)
				if desc, _ := prop["description"].(string); desc == "" {
					t.Errorf("input property %q has no description", propName)
				}
			}
			for _, req := range c.inputRequired {
				if !required[req] {
					t.Errorf("input property %q should be required", req)
				}
			}
			for _, opt := range c.inputOptional {
				if required[opt] {
					t.Errorf("input property %q should be optional", opt)
				}
			}

			outProps := schemaProperties(t, tool.OutputSchema)
			for _, field := range c.outputFields {
				if _, ok := outProps[field]; !ok {
					t.Errorf("output schema missing field %q (have %v)", field, keys(outProps))
				}
			}
		})
	}
}

func schemaProperties(t *testing.T, schema any) map[string]any {
	t.Helper()
	if schema == nil {
		return map[string]any{}
	}
	m, ok := schema.(map[string]any)
	if !ok {
		t.Fatalf("schema is %T, want a JSON object", schema)
	}
	props, _ := m["properties"].(map[string]any)
	return props
}

func schemaRequired(schema any) map[string]bool {
	req := map[string]bool{}
	m, ok := schema.(map[string]any)
	if !ok {
		return req
	}
	arr, _ := m["required"].([]any)
	for _, r := range arr {
		if s, ok := r.(string); ok {
			req[s] = true
		}
	}
	return req
}

func keys(m map[string]any) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func sameSet(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	seen := map[string]bool{}
	for _, x := range a {
		seen[x] = true
	}
	for _, x := range b {
		if !seen[x] {
			return false
		}
	}
	return true
}

func toolNames(m map[string]*mcp.Tool) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
